package com.rijaldev.herbalplants

object HerbalsData {
    private val herbalNames = arrayOf(
        "Asam Jawa",
        "Bawang Merah",
        "Bawang Putih",
        "Cabai",
        "Cengkeh",
        "Daun Mint",
        "Daun Sirih",
        "Jahe",
        "Jinten",
        "Kunyit",
        "Lada",
        "Mengkudu",
        "Pala",
        "Seledri",
        "Serai"
    )

    private val herbalDetails = arrayOf(
        "Sebagai salah satu rempah pilihan yang sering digunakan dalam bumbu masakan, asam jawa ternyata menawarkan segudang manfaat untuk kesehatan Anda. Asam jawa atau tamarin adalah tumbuhan khas daerah tropis yang sangat mudah ditemukan di sekitar kita. Sebagai bumbu dapur, ternyata asam jawa mengandung banyak nutrisi. \n\nMenurut Data Komposisi Gizi Pangan, dalam 100 gram asam jawa terdapat zat-zat berikut: Air: 31.4 g, Energi: 267 Kal, Protein: 2.8 g, Lemak: 0.6 g, Karbohidrat: 62.5 g, Serat pangan: 1.2 g, Kalsium: 74 mg, Fosfor: 113 mg, Zat besi: 0.6 mg, Natrium: 9 mg, Kalium: 139.5 mg, Tembaga: 0.09 mg, Zink: 0.1 mg, Beta-Karoten: 9 mcg, Karoten Total: 30 mcg, Thiamin (Vitamin B1): 0.34 mg, Riboflavin (Vitamin B2): 0.04 mg, dan Vitamin C : 2 mg. \n\nBerikut ini adalah sejumlah manfaat asam jawa bagi Kesehatan: \n- Menjaga kesehatan sistem pencernaan \n- Menjaga kesehatan jantung \n- Membantu mengontrol gula darah \n- Membantu menurunkan berat badan \n- Membantu melindungi organ hati \n- Menjaga kesehatan gigi \n- Mencegah infeksi jamur \n- Meredakan mual.",
        "Hampir semua makanan Indonesia menggunakan bawang merah sebagai salah satu bumbu masakannya. Tidak hanya membuat makanan menjadi lebih sedap dan kaya rasa, bawang merah ternyata juga mempunyai manfaat bagi kesehatan karena kaya kandungan gizi. Manfaat dari bawang merah ini bukan hanya sekadar jadi penyedap saja, tapi juga memberikan berbagai nutrisi yang dibutuhkan tubuh. Dalam 100 gram bawang merah, terdapat kandungan nutrisi berikut ini. Protein: 1,5 gram, Lemak: 0,3 gram, Karbohidrat: 9.2 gram, Serat: 1.7 gram,Kalsium: 36 mg, Fosfor: 40 mg, Zat besi: 0,8 mg, Natrium: 7 mg, Kalium: 178,6 mg, Tembaga: 0,06 mg, Seng: 0,2 mg, Thiamin (vitamin B1): 0,03 mg, Riboflavin (vitamin B2): 0,04 mg, Niasin (Vitamin B3): 0,2 mg, Vitamin C: 2 mg. \n\nBerdasarkan kandungan nutrisinya, bawang merah kemungkinan memberikan manfaat jika Anda konsumsi secara rutin, seperti berikut ini: \n- Memiliki potensi mencegah kanker \n- Mengatasi peradangan\n- Mendukung kesehatan saraf dan otot \n- Menyehatkan tulang \n- Memiliki potensi meningkatkan sistem imun",
        "Meski bawang putih memiliki aroma yang menyengat, ada banyak manfaat bawang putih bagi kesehatan. Bukan hanya sebagai pelezat masakan, bawang putih telah lama digunakan untuk mencegah dan mengatasi berbagai penyakit. Hal ini adalah berkat kandungan nutrisi di dalamnya. Bawang putih merupakan jenis bawang yang dapat ditemukan di seluruh dunia. Bau yang menyengat pada bawang putih berasal dari kandungan sulfur organik, yang juga bermanfaat untuk menjaga kesehatan tubuh. Bawang putih juga sering digunakan untuk mengatasi kondisi medis yang berhubungan dengan jantung dan sistem peredaran darah, seperti tekanan darah tinggi, kolesterol tinggi, dan pengerasan pembuluh darah (aterosklerosis). \n\nBerikut ini adalah kandungan nutrisi di dalam 100 gram bawang putih mentah 6,3 gram protein, 0,5 gram lemak, 33 gram karbohidrat, 2,1 gram serat, 181 mg kalsium, 1,7 mg zat besi, 25 mg magnesium, 153 mg fosfor, 401 mg kalium. Selain itu, bawang putih juga mengandung senyawa yang berfungsi sebagai antioksidan, antibakteri, antikanker, dan antiradang. \n\nBerkat kandungan nutrisinya, bawang putih memiliki beragam manfaat. Beberapa manfaat bawang putih bagi kesehatan yang sudah cukup dikenal adalah: \n- Menjaga kesehatan jantung \n- Menjaga kesehatan saluran pencernaan \n- Mencegah kanker \n- Mencegah penyakit Alzheimer \n- Mencegah pilek.",
        "Di balik rasa yang pedas, ada beragam manfaat cabai untuk kesehatan. Manfaat ini dapat diperoleh karena cabai mengandung berbagai macam nutrisi penting yang dibutuhkan tubuh. Ada beragam nutrisi di dalam cabai yang bermanfaat untuk kesehatan, termasuk protein, karbohidrat, gula, serat, lemak, vitamin A, vitamin B6, vitamin C, zat besi, magnesium, kalium, air dan capsaicin. Namun, jangan sampai mengonsumsi cabai berlebihan, karena dapat menyebabkan gangguan pencernaan. Makanan pedas ini juga sebaiknya diberikan secara bertahap pada anak-anak. \n\nJika dikonsumsi sewajarnya, manfaat cabai yang dapat diperoleh di antaranya adalah: \n- Mengatasi hidung tersumbat \n- Meredakan nyeri \n- Meningkatkan imunitas tubuh \n- Mengurangi risiko terserang penyakit jantung \n- Mencegah penyakit kanker \n- Membakar lemak tubuh \n- Memperpanjang umur.",
        "Cengkeh merupakan salah satu rempah serbaguna yang sering digunakan dalam membuat makanan, minuman, dan bahkan sebagai campuran dalam pembuatan rokok. Di balik kegunaannya tersebut, cengkeh juga kerap dimanfaatkan sebagai obat-obatan tradisional. Cengkeh yang memiliki nama latin Syzygium aromaticum adalah tangkai bunga kering yang berasal dari keluarga pohon Mirtaceae. Sejak berabad-abad lalu, cengkeh sudah dijadikan sebagai bumbu rempah dalam masakan sekaligus obat herbal. Selain daun, bunga, dan buahnya, minyak cengkeh juga sering dimanfaatkan sebagai aromaterapi dan obat oles untuk meredakan sakit gigi. Dalam satu sendok teh atau sekitar 2 gram cengkeh, terkandung energi sebesar 21 kalori, 1 gram serat, dan 1 gram karbohidrat. Cengkeh juga mengandung nutrisi lain seperti kalium, mangan, kalsium, magnesium, natrium, zinc, folat, antioksidan, vitamin A, vitamin C, vitamin E, dan vitamin K. Maka tak heran, berbagai nutrisi tersebut mendukung manfaat cengkeh untuk kesehatan tubuh. \n\nBerbagai pemanfaatan cengkeh dalam dunia kesehatan, di antaranya: \n- Mengurangi sakit gigi \n- Membantu mengobati tukak lambung \n- Menghambat pertumbuhan bakteri \n- Mencegah ejakulasi dini \n- Menjaga kesehatan hati \n- Menjaga kesehatan tulang \n- Pereda nyeri.",
        "Di balik sensasi rasanya yang dingin dan menyegarkan, ternyata ada banyak manfaat daun mint untuk kesehatan, mulai dari menjaga kesehatan gigi, meringankan kram menstruasi, hingga meningkatkan fungsi otak. Daun mint masih merupakan salah satu daun herba yang masih berkerabat dengan daun herba lain, yakni daun sage. Meski berukuran kecil, daun mint memiliki berbagai kandungan nutrisi. Daun herba ini diketahui merupakan salah satu tanaman sumber vitamin A yang baik untuk kesehatan mata. Selain itu, daun mint juga sangat kaya akan antioksidan yang berperan untuk menangkal radikal bebas dalam tubuh. \n\nBerkat kandungan nutrisi di dalamnya, daun mint memiliki beragam manfaat bagi kesehatan, seperti: \n- Menjaga kesehatan gigi \n- Meringankan kram menstruasi \n- Mengatasi gangguan pencernaan \n- Meredakan sakit kepala \n- Meningkatkan fungsi otak.",
        "Manfaat daun sirih merah bagi kesehatan sudah diketahui sejak dahulu kala. Berkat manfaatnya ini, daun sirih merah digunakan secara turun-temurun di Indonesia sebagai salah satu obat tradisional untuk menangani sejumlah masalah kesehatan. Di Indonesia, daun sirih merah (Piper crocatum) biasanya dikonsumsi dengan cara diminum air rebusannya atau dikunyah langsung. Selain itu, ada juga suplemen yang dibuat dari ekstrak daun sirih merah. Anda bisa mendapatkan manfaat daun sirih merah berkat beragam senyawa yang terkandung di dalamnya, seperti flavonoid, fenol, alkaloid, polifenolat, tanin, saponin, dan senyawa minyak atsiri. \n\nManfaat daun sirih merah bagi kesehatan diantaranya adalah: \n- Mempercepat penyembuhan luka\n- Mencegah infeksi bakteri\n- Mengobati rheumatoid arthritis \n- Melawan radikal bebas \n- Mengobati diabetes \n- Mencegah pembentukan plak gigi.",
        "Jahe merupakan tanaman herba yang kerap dimanfaatkan untuk mengatasi berbagai kondisi, mulai dari mual, batuk, nyeri sendi, hingga nyeri akibat terapi kanker. Namun jika ditinjau dari segi medis, setidaknya ada lima manfaat jahe yang baik bagi tubuh. Jahe merupakan tanaman herba yang masih berkerabat dengan kencur. Jahe memiliki senyawa kimia yang dipercaya bisa bereaksi positif di dalam lambung dan usus hingga mampu mengurangi mual dan nyeri. Senyawa tersebut juga diduga bisa bekerja baik di otak dan sistem saraf guna meredam rasa mual. Di samping itu, masih banyak manfaat jahe lainnya yang bisa kita dapatkan. \n\nBerikut lima kondisi yang diyakini dapat diatasi dengan mengonsumsi jahe: \n- Meredakan pusing \n- Mengurangi nyeri menstruasi \n- Mencegah morning sickness, \n- Osteoarthritis \n- Mengurangi rasa mual dan muntah usai operasi ",
        "Jintan hitam (black seed), atau biasa dikenal juga oleh masyarakat Indonesia sebagai habbatussauda, sudah lama digunakan secara luas sebagai obat herba. Penelitian menunjukkan tanaman ini memiliki manfaat kesehatan dan mampu mengatasi berbagai penyakit. Biji-bijian yang dalam bahasa Latin disebut Nigella sativa ini biasa diolah untuk dijadikan bumbu masakan atau diambil ekstraknya. Sejak masa lampau, habbatussauda telah digunakan untuk menangani berbagai penyakit dan dipercaya memiliki manfaat baik bagi kesehatan. \n\nJintan hitam mengandung aneka nutrisi yang baik bagi kesehatan, seperti karbohidrat, protein, lemak sehat termasuk asam oleat dan asam linoleat, kalsium, serat, zat besi, natrium, kalium, dan antioksidan. Berbagai penelitian telah dilakukan untuk membuktikan manfaat pengobatan yang dimiliki habbatussauda. Di antaranya untuk membantu pengobatan diabetes, hipertensi, kolesterol tinggi, dan kanker. Selain itu, jintan hitam juga memiliki efek antibakteri, diuretik, antiperadangan, analgesik, memperkuat kekebalan tubuh, dan baik untuk kesehatan organ ginjal, lambung, serta hati. Manfaat tersebut berasal dari thymoquinone (TQ) yang terkandung dalam habbatussauda, Dengan manfaatnya yang banyak ini, jintan hitam memberikan kesan sebagai obat herbal yang dapat mengobati berbagai penyakit. \n\nBerikut khasiat jinten hitam dipandang dari sisi medis: \n- Mengobati darah tinggi (hipertensi) \n- Mengobati kolesterol tinggi \n- Menjaga kadar gula darah \n- Memiliki efek antiradang \n- Melawan infeksi \n- Melindungi hati \n- Mencegah kanker ",
        "Kunyit dikenal sebagai bumbu dapur. Meski begitu, manfaat kunyit tak hanya untuk melezatkan masakan, tetapi juga baik untuk kesehatan, seperti mencegah kanker dan menurunkan risiko terkena penyakit jantung. Selain itu, masih ada banyak manfaat kunyit untuk kesehatan. Selain sebagai bahan masakan, kunyit juga telah digunakan sejak lama dalam pengobatan tradisional. Hal ini karena kandungan kurkumin yang terdapat pada rimpang kunyit. Selain memberi warna pada kunyit, kurkumin juga diduga memiliki khasiat yang baik untuk kesehatan tubuh. Di dalam 100 gram kunyit, terkandung beragam nutrisi berikut ini: 10 gram protein, 168 miligram kalsium, 208 miligram magnesium, 299 miligram fosfor, 2 gram kalium, 1 miligram vitamin C, 55 miligram zat besi. Selain beberapa nutrisi di atas, kunyit juga mengandung senyawa yang bersifat antioksidan, antiinflamasi, dan antimikroba yang sangat bermanfaat bagi kesehatan tubuh.\n\nBerkat kandungan nutrisi yang telah disebutkan di atas, kunyit memiliki beragam manfaat yang baik untuk kesehatan, seperti: \n- Mengurangi nyeri pada penderita osteoarthritis \n- Mencegah penyakit jantung \n- Meredakan rasa gatal pada kulit \n- Meringankan gangguan menstruasi \n- Mengatasi gangguan saluran pencernaan \n- Mencegah kanker \n- Mengurangi depresi \n- Mengatasi masalah kulit",
        "Lada atau merica merupakan salah satu bumbu dapur yang paling banyak digunakan dalam masakan, khususnya masakan Indonesia. Ada dua jenis lada yang dikenal oleh masyarakat, yaitu lada hitam dan lada putih. Namun, tahukah Anda selain dipakai sebagai bumbu dapur, ternyata terselip manfaat lada dalam bidang kesehatan yang sayang untuk dilewatkan. Lada sendiri merupakan buah mentah yang dihasilkan dari tanaman Piper nigrum. Sejarah mencatat bahwa pada abad ke\n-18, penjelajah asal Portugis bernama Vasco de Gama, sudah memimpin ekspedisi dalam misi mencari keberadaan lada untuk diperdagangkan. Selain menjadi komoditas yang paling banyak diperdagangkan di seluruh dunia, ternyata lada juga sudah lama dimanfaatkan dalam pengobatan tradisional di India. Hingga kini, ada yang menganggap manfaat lada dapat menyembuhkan kondisi tertentu, seperti sakit perut, bronkitis, malaria, dan kolera, meski teori ini masih perlu mendapat pembuktian lebih lanjut. Lada merupakan jenis rempah yang mengandung berbagai nutrisi yang baik untuk kesehatan. \n\nSatu sendok teh lada mengandung 6 kalori, 0,2 gram protein, 1,4 gram karbohidrat, dan 0,6 gram serat. Tak hanya itu, lada juga mengandung kalsium, zat besi, magnesium, fosfor, kalium, vitamin A, B1, B2, B3, B6, serta vitamin K, meskipun dalam jumlah yang sedikit. Dengan nutrisi inilah, tidak heran jika lada dapat memberikan manfaat kesehatan bagi tubuh. \n\nBerikut adalah beberapa manfaat lada untuk kesehatan, yaitu: \n- Meredakan hidung tersumbat \n- Mencegah kerusakan sel \n- Menghambat pertumbuhan bakteri \n- Membantu mengobati penyakit lambung \n- Mampu meredakan radang sendi \n- Mengontrol kadar gula darah",
        "Manfaat buah mengkudu untuk kesehatan telah dikenal sejak lama. Meski memiliki rasa yang sangat pahit, tidak sedikit masyarakat Indonesia yang menggunakan buah ini untuk mengobati berbagai penyakit, mulai dari sakit kepala, flu, hingga diabetes. Mengkudu (Morinda citrifolia) merupakan buah berwarna hijau yang banyak ditemukan di Australia, India, dan Asia Tenggara, termasuk Indonesia. Buah ini cukup populer dikonsumsi sebagai obat herbal dan suplemen. Di dalam buah mengkudu, terkandung beragam nutrisi berikut ini: Karbohidrat, Protein, Gula, Vitamin C, Vitamin E, Biotin, Folat, Magnesium, Kalium, dan Kalsium. Buah mengkudu juga kaya akan antioksidan, seperti flavonoid dan saponin, serta berbagai zat yang bersifat antiradang dan antibakteri. Selain dipercaya dapat mengobati berbagai jenis penyakit, buah mengkudu juga dipercaya dapat melembapkan kulit dan menyamarkan kerutan halus di wajah. Sayangnya, efektivitas buah mengkudu tersebut masih memerlukan penelitian lebih lanjut. Buah mengkudu memang memiliki bau yang menyengat dan rasa yang pahit. \n\nMeski demikian, manfaat buah mengkudu untuk kesehatan sangatlah beragam, di antaranya: \n- Mencegah dan memperbaiki kerusakan sel tubuh \n- Menjaga kadar kolesterol dalam darah \n- Mengurangi nyeri sendi \n- Meningkatkan sistem kekebalan tubuh \n- Menurunkan kadar gula darah \n- Menjaga berat badan tetap ideal ",
        "Buah pala adalah salah satu jenis rempah-rempah yang terkenal dan digunakan sebagai bahan tambahan masakan. Selain itu, buah pala juga memiliki banyak manfaat untuk kesehatan tubuh. Berikut beberapa manfaat buah pala dan kandungan nutrisinya. Dalam 100 gram buah pala terdapat 525 kalori. Berikut adalah kandungan zat gizi yang bisa Anda dapatkan dari sekitar 100 gram buah pala. Lemak total: 36 gram Protein: 6 gram, Sodium: 16 miligram, Zat besi, Kalsium, Vitamin A, Vitamin C. \n\nSetelah mengetahui kandungan nutrisi dalam buah pala, berikut beberapa manfaat buah pala untuk kesehatan tubuh: \n- Meningkatkan kesehatan otak \n- Mengurangi rasa sakit \n- Mengatasi masalah pencernaan \n- Menjaga kesehatan mulut \n- Mengobati Insomnia \n- Membantu mengeluarkan racun dari tubuh \n- Merawat kulit \n- Mengendalikan tekanan darah",
        "Daun seledri banyak dimanfaatkan sebagai pelengkap masakan di Indonesia. Biasanya daun seledri segar dicincang dan ditaburkan di atas masakan. Tidak hanya membuat makanan semakin nikmat, manfaat daun seledri untuk kesehatan juga cukup banyak. Menurut penelitian, daun seledri memiliki kandungan antioksidan yang cukup tinggi. Antioksidan merupakan suatu zat yang berfungsi mengurangi kerusakan sel tubuh akibat proses oksidasi dan radikal bebas. \n\nKandungan yang dimiliki daun seledri, membuatnya banyak digunakan sebagai salah satu bahan pembuatan obat-obatan. Berbagai penelitian dilakukan untuk membuktikan manfaat seledri, termasuk biji, batang dan daun seledri. Untuk memahaminya lebih jauh, di bawah ini adalah beberapa potensi manfaat daun seledri untuk kesehatan: \n- Menurunkan tekanan darah \n- Mencegah kanker \n- Melancarkan pencernaan \n- Meredakan nyeri haid \n- Mengusir nyamuk",
        "Manfaat sereh untuk kesehatan erat dikaitkan dengan kandungan nutrisi di dalamnya. Selain membuat cita rasa makanan dan minuman menjadi lebih lezat, sereh juga mengandung berbagai macam nutrisi yang dibutuhkan tubuh, seperti vitamin B, magnesium, kalium dan zat besi. Untuk mendapatkan manfaat sereh, Anda dapat mengonsumsi makanan ataupun minuman yang mengandung sereh. Anda juga bisa menjadikan minyak sereh sebagai aromaterapi yang menenangkan. Sereh dipercaya memiliki beragam manfaat bagi kesehatan. \n\nBerikut beberapa manfaat di antaranya: \n- Mengatasi gigi berlubang \n- Melawan radikal bebas \n- Mengontrol tekanan darah \n- Meringankan gejala sindrom pramenstruasi \n- Mengatur fungsi otot \n- Mengatasi kecemasan \n- Menurunkan berat badan"
    )

    private val herbalImages = intArrayOf(
        R.drawable.asam_jawa,
        R.drawable.bawang_merah,
        R.drawable.bawang_putih,
        R.drawable.cabai,
        R.drawable.cengkeh,
        R.drawable.daun_mint,
        R.drawable.sirih,
        R.drawable.jahe,
        R.drawable.habbatus_sauda,
        R.drawable.kunyit,
        R.drawable.lada,
        R.drawable.mengkudu,
        R.drawable.pala,
        R.drawable.seledri,
        R.drawable.serai
    )

    val listData: ArrayList<Herbal>
        get() {
            val list = arrayListOf<Herbal>()
            for (position in herbalNames.indices) {
                val herbal = Herbal()
                herbal.name = herbalNames[position]
                herbal.detail = herbalDetails[position]
                herbal.photo = herbalImages[position]
                list.add(herbal)
            }
            return list
        }
}